<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Enterprise.TransactionPlatform.Application\Enterprise.TransactionPlatform.Application.csproj" />
    <ProjectReference Include="..\Enterprise.TransactionPlatform.Domain\Enterprise.TransactionPlatform.Domain.csproj" />
  </ItemGroup>

</Project>
